using System.Text;
using Tempest.Model;

namespace Tempest.Emit;

/// <summary>
/// <see cref="ComponentModel"/> -> generated C# source text. Emits one state twin per
/// member: a {Name}State CommandState property per [Command], a {PascalCase}State
/// ReactiveState&lt;T&gt; property per [Reactive] field (invoking its [OnChanged] hook
/// when one is wired), and the bus registration override per [Event].
/// The emitted code is framework-neutral: it references only Tempest.Core types
/// (CommandState, ReactiveState, IEventBus) plus the small host-base surface
/// (InvokeAsync, SubscribeEvent, DispatchEvent, RegisterTempestHandlers).
/// </summary>
public sealed class Emitter
{
    private const string TaskType = "global::System.Threading.Tasks.Task";

    /// <summary>The stable hint name for a component's generated file:
    /// "{Namespace}.{Name}.Tempest.g.cs", or "{Name}.Tempest.g.cs" when the component
    /// lives in the global namespace.</summary>
    public static string HintName(ComponentModel component)
        => component.Namespace.Length == 0
            ? $"{component.Name}.Tempest.g.cs"
            : $"{component.Namespace}.{component.Name}.Tempest.g.cs";

    /// <summary>Emits the complete generated partial-class source for one component.</summary>
    public string Emit(ComponentModel component)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Tempest />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // Members parsed out of .razor files carry their type names as written, so give
        // the generated file the usings those names rely on.
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        foreach (var directive in component.Usings)
            sb.AppendLine($"using {directive};");
        sb.AppendLine();

        var indent = "";
        if (component.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {component.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}partial class {component.Name}");
        sb.AppendLine($"{indent}{{");

        var body = indent + "    ";

        foreach (var m in component.Methods)
        {
            if (m.IsCommand)
                EmitCommandState(sb, body, m);
        }

        foreach (var r in component.Reactives)
            EmitReactiveState(sb, body, r);

        EmitRegisterTempestHandlers(sb, body, component);

        sb.AppendLine($"{indent}}}");
        if (component.Namespace.Length > 0)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitCommandState(StringBuilder sb, string body, MethodModel m)
    {
        // Plain [Command]: named after the method. [Event, Command]: named after the record.
        var name = m.IsEvent ? m.ParamTypeName! : m.MethodName;
        var backing = $"__{char.ToLowerInvariant(name[0])}{name.Substring(1)}State";

        // Result-bearing return types get a CommandState<TResult>; event commands stay
        // resultless (the bus publisher has no way to receive a value anyway).
        var stateType = m.IsEvent
            ? $"global::Tempest.EventCommandState<{m.ParamType}>"
            : m.Kind is ReturnKind.TaskOfT or ReturnKind.ValueTaskOfT or ReturnKind.Sync
                ? $"global::Tempest.CommandState<{m.ResultType}>"
                : "global::Tempest.CommandState";

        var args = m.IsEvent
            ? (m.HasCancellationToken ? "__e, __ct" : "__e")
            : (m.HasCancellationToken ? "__ct" : "");
        var lambdaParams = m.IsEvent ? "(__e, __ct)" : "__ct";
        var call = $"{m.MethodName}({args})";
        var command = m.Kind switch
        {
            ReturnKind.Task or ReturnKind.TaskOfT => $"{lambdaParams} => {call}",
            ReturnKind.ValueTask or ReturnKind.ValueTaskOfT => $"{lambdaParams} => {call}.AsTask()",
            ReturnKind.Sync when !m.IsEvent => $"{lambdaParams} => {TaskType}.FromResult({call})",
            _ => $"{lambdaParams} => {{ {call}; return {TaskType}.CompletedTask; }}",
        };

        sb.AppendLine($"{body}private {stateType}? {backing};");
        sb.AppendLine();
        sb.AppendLine($"{body}/// <summary>State for the {name} command: IsLoading, Error, Execute, TryExecute.</summary>");
        sb.AppendLine($"{body}{m.Accessibility} {stateType} {name}State => {backing} ??= new {stateType}(this, {command});");
        sb.AppendLine();
    }

    private static void EmitReactiveState(StringBuilder sb, string body, ReactiveModel r)
    {
        var backing = $"__{char.ToLowerInvariant(r.PropertyName[0])}{r.PropertyName.Substring(1)}State";
        var stateType = $"global::Tempest.ReactiveState<{r.TypeText}>";

        // The [OnChanged] hook is an ordinary user method — invoked directly, adapted
        // with CompletedTask when it returns void. No partial counterpart is generated.
        var hookArgument = r.Hook switch
        {
            null => "null",
            { ReturnsTask: true } hook => $"__v => {hook.MethodName}(__v)",
            { } hook => $"__v => {{ {hook.MethodName}(__v); return {TaskType}.CompletedTask; }}",
        };

        sb.AppendLine($"{body}private {stateType}? {backing};");
        sb.AppendLine();
        sb.AppendLine($"{body}/// <summary>State for the {r.FieldName} field: Value, SetSilently, IsDirty, Reset.</summary>");
        sb.AppendLine($"{body}{r.Accessibility} {stateType} {r.PropertyName}State => {backing} ??= new {stateType}(");
        sb.AppendLine($"{body}    this,");
        sb.AppendLine($"{body}    () => {r.FieldName},");
        sb.AppendLine($"{body}    __v => {r.FieldName} = __v,");
        sb.AppendLine($"{body}    {r.FieldName},");
        sb.AppendLine($"{body}    {hookArgument});");
        sb.AppendLine();
    }

    private static void EmitRegisterTempestHandlers(StringBuilder sb, string body, ComponentModel component)
    {
        var events = new List<MethodModel>();
        foreach (var m in component.Methods)
        {
            if (m.IsEvent)
                events.Add(m);
        }

        if (events.Count == 0 && component.Reactives.Count == 0)
            return;

        sb.AppendLine($"{body}protected override void RegisterTempestHandlers(global::Tempest.IEventBus bus)");
        sb.AppendLine($"{body}{{");
        foreach (var m in events)
        {
            var subscription = m switch
            {
                // Bus-triggered commands run through TryExecute so a publish can't
                // blow up in the publisher; the error lands in {Name}State.Error.
                { IsCommand: true } =>
                    $"SubscribeEvent<{m.ParamType}>(e => InvokeAsync(() => {m.ParamTypeName}State.TryExecute(e)));",
                { Kind: ReturnKind.Task or ReturnKind.TaskOfT } =>
                    $"SubscribeEvent<{m.ParamType}>(e => DispatchEvent(() => {m.MethodName}(e)));",
                { Kind: ReturnKind.ValueTask or ReturnKind.ValueTaskOfT } =>
                    $"SubscribeEvent<{m.ParamType}>(e => DispatchEvent(() => {m.MethodName}(e).AsTask()));",
                _ =>
                    $"SubscribeEvent<{m.ParamType}>(e => DispatchEvent(() => {{ {m.MethodName}(e); }}));",
            };
            sb.AppendLine($"{body}    {subscription}");
        }
        foreach (var r in component.Reactives)
        {
            // Touch each reactive state so Initial captures the field's initializer value.
            sb.AppendLine($"{body}    _ = {r.PropertyName}State;");
        }
        sb.AppendLine($"{body}}}");
    }
}

