using System.Text;
using Tempest.Compiler;
using Tempest.Parsing;
using Tempest.Pipeline;

namespace Tempest.Emit;

/// <summary><see cref="CompiledComponent"/> → generated C# source — the exposed surface
/// of this library. Emits one state twin per member: a {Name}State CommandState
/// property per [Command], a {PascalCase}State ReactiveState&lt;T&gt; property per
/// [Reactive] field (invoking its [OnChanged] hook when one is wired), and the bus
/// registration override per [Event]. The emitted code is framework-neutral: it
/// references only Tempest.Abstract types (CommandState, ReactiveState, IEventBus) plus the
/// small host-base surface (InvokeAsync, SubscribeEvent, DispatchEvent,
/// RegisterTempestHandlers) — Blazor vs XAML vs store is a runtime base-class
/// difference, never a codegen fork.</summary>
public sealed class TempestEmitter
{
    private const string TaskType = "global::System.Threading.Tasks.Task";

    public Result<GeneratedFile> Emit(CompiledComponent? component)
    {
        if (InvalidEmitInputError.Check(component) is { } invalid)
            return Result<GeneratedFile>.Fail(invalid);

        return Result<GeneratedFile>.Ok(new GeneratedFile(HintName(component!), Source(component!)));
    }

    /// <summary>The stable hint name: "{Namespace}.{Name}.Tempest.g.cs", or
    /// "{Name}.Tempest.g.cs" when the component lives in the global namespace.</summary>
    private static string HintName(CompiledComponent component)
        => component.Namespace.Length == 0
            ? $"{component.Name}.Tempest.g.cs"
            : $"{component.Namespace}.{component.Name}.Tempest.g.cs";

    private static string Source(CompiledComponent component)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Tempest />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        // Members parsed out of .razor files carry their type names as written, so give
        // the generated file the usings those names rely on.
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        foreach (var directive in component.Usings)
            sb.AppendLine($"using {directive};");
        sb.AppendLine();

        var indent = "";
        if (component.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {component.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}partial class {component.Name}");
        sb.AppendLine($"{indent}{{");

        var body = indent + "    ";

        foreach (var method in component.Methods)
        {
            if (method.IsCommand)
                WriteCommandState(sb, body, method);
        }

        foreach (var reactive in component.Reactives)
            WriteReactiveState(sb, body, reactive);

        WriteRegisterTempestHandlers(sb, body, component);

        sb.AppendLine($"{indent}}}");
        if (component.Namespace.Length > 0)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void WriteCommandState(StringBuilder sb, string body, CompiledMethod method)
    {
        // Plain [Command]: named after the method. [Event, Command]: named after the record.
        var name = method.IsEvent ? method.ParamTypeName! : method.MethodName;
        var backing = $"__{char.ToLowerInvariant(name[0])}{name.Substring(1)}State";

        // Result-bearing return types get a CommandState<TResult>; event commands stay
        // resultless (the bus publisher has no way to receive a value anyway).
        var stateType = method.IsEvent
            ? $"global::Tempest.EventCommandState<{method.ParamType}>"
            : method.Kind is ReturnKind.TaskOfT or ReturnKind.ValueTaskOfT or ReturnKind.Sync
                ? $"global::Tempest.CommandState<{method.ResultType}>"
                : "global::Tempest.CommandState";

        var args = method.IsEvent
            ? (method.HasCancellationToken ? "__e, __ct" : "__e")
            : (method.HasCancellationToken ? "__ct" : "");
        var lambdaParams = method.IsEvent ? "(__e, __ct)" : "__ct";
        var call = $"{method.MethodName}({args})";
        var command = method.Kind switch
        {
            ReturnKind.Task or ReturnKind.TaskOfT => $"{lambdaParams} => {call}",
            ReturnKind.ValueTask or ReturnKind.ValueTaskOfT => $"{lambdaParams} => {call}.AsTask()",
            ReturnKind.Sync when !method.IsEvent => $"{lambdaParams} => {TaskType}.FromResult({call})",
            _ => $"{lambdaParams} => {{ {call}; return {TaskType}.CompletedTask; }}",
        };

        // A wired [CanExecute] member becomes the state's ICommand predicate.
        var canExecute = method.CanExecute switch
        {
            null => "",
            { IsMethod: true } gate => $", () => {gate.MemberName}()",
            { } gate => $", () => {gate.MemberName}",
        };

        sb.AppendLine($"{body}private {stateType}? {backing};");
        sb.AppendLine();
        sb.AppendLine($"{body}/// <summary>State for the {name} command: IsLoading, Error, Execute, TryExecute.</summary>");
        sb.AppendLine($"{body}{method.Accessibility} {stateType} {name}State => {backing} ??= new {stateType}(this, {command}{canExecute});");
        sb.AppendLine();
    }

    private static void WriteReactiveState(StringBuilder sb, string body, CompiledReactive reactive)
    {
        var backing = $"__{char.ToLowerInvariant(reactive.PropertyName[0])}{reactive.PropertyName.Substring(1)}State";
        var stateType = $"global::Tempest.ReactiveState<{reactive.TypeText}>";

        // The [OnChanged] hook is an ordinary user method — invoked directly, adapted
        // with CompletedTask when it returns void. No partial counterpart is generated.
        var hookArgument = reactive.Hook switch
        {
            null => "null",
            { ReturnsTask: true } hook => $"__v => {hook.MethodName}(__v)",
            { } hook => $"__v => {{ {hook.MethodName}(__v); return {TaskType}.CompletedTask; }}",
        };

        sb.AppendLine($"{body}private {stateType}? {backing};");
        sb.AppendLine();
        sb.AppendLine($"{body}/// <summary>State for the {reactive.FieldName} field: Value, SetSilently, IsDirty, Reset.</summary>");
        sb.AppendLine($"{body}{reactive.Accessibility} {stateType} {reactive.PropertyName}State => {backing} ??= new {stateType}(");
        sb.AppendLine($"{body}    this,");
        sb.AppendLine($"{body}    () => {reactive.FieldName},");
        sb.AppendLine($"{body}    __v => {reactive.FieldName} = __v,");
        sb.AppendLine($"{body}    {reactive.FieldName},");
        sb.AppendLine($"{body}    {hookArgument});");
        sb.AppendLine();
    }

    private static void WriteRegisterTempestHandlers(StringBuilder sb, string body, CompiledComponent component)
    {
        var events = new List<CompiledMethod>();
        var runOnLoad = new List<CompiledMethod>();
        foreach (var method in component.Methods)
        {
            if (method.IsEvent)
                events.Add(method);
            if (method.RunOnLoad)
                runOnLoad.Add(method);
        }

        if (events.Count == 0 && component.Reactives.Count == 0 && runOnLoad.Count == 0)
            return;

        sb.AppendLine($"{body}protected override void RegisterTempestHandlers(global::Tempest.IEventBus bus)");
        sb.AppendLine($"{body}{{");
        foreach (var method in events)
        {
            var subscription = method switch
            {
                // Bus-triggered commands run through TryExecute so a publish can't
                // blow up in the publisher; the error lands in {Name}State.Error.
                { IsCommand: true } =>
                    $"SubscribeEvent<{method.ParamType}>(e => InvokeAsync(() => {method.ParamTypeName}State.TryExecute(e)));",
                { Kind: ReturnKind.Task or ReturnKind.TaskOfT } =>
                    $"SubscribeEvent<{method.ParamType}>(e => DispatchEvent(() => {method.MethodName}(e)));",
                { Kind: ReturnKind.ValueTask or ReturnKind.ValueTaskOfT } =>
                    $"SubscribeEvent<{method.ParamType}>(e => DispatchEvent(() => {method.MethodName}(e).AsTask()));",
                _ =>
                    $"SubscribeEvent<{method.ParamType}>(e => DispatchEvent(() => {{ {method.MethodName}(e); }}));",
            };
            sb.AppendLine($"{body}    {subscription}");
        }
        foreach (var reactive in component.Reactives)
        {
            // Touch each reactive state so Initial captures the field's initializer value.
            sb.AppendLine($"{body}    _ = {reactive.PropertyName}State;");
        }
        foreach (var method in runOnLoad)
        {
            // [RunOnLoad]: fire-safe, so a failing load lands in {Name}State.Error.
            sb.AppendLine($"{body}    _ = {method.MethodName}State.TryExecute();");
        }
        sb.AppendLine($"{body}}}");
    }
}
