<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tempest.Compiler\Tempest.Compiler.csproj" />
    <ProjectReference Include="..\Tempest.Parsing\Tempest.Parsing.csproj" />
    <ProjectReference Include="..\Tempest.Pipeline\Tempest.Pipeline.csproj" />
  </ItemGroup>

</Project>
