// <auto-generated by Tempest />
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tempest.Samples
{
    partial class Todo
    {
        private global::Tempest.CommandState<List<TodoItem>>? __loadState;

        /// <summary>State for the Load command: IsLoading, Error, Execute, TryExecute.</summary>
        private global::Tempest.CommandState<List<TodoItem>> LoadState => __loadState ??= new global::Tempest.CommandState<List<TodoItem>>(this, __ct => Load(__ct));

        private global::Tempest.CommandState? __addState;

        /// <summary>State for the Add command: IsLoading, Error, Execute, TryExecute.</summary>
        private global::Tempest.CommandState AddState => __addState ??= new global::Tempest.CommandState(this, __ct => Add(__ct));

        private global::Tempest.ReactiveState<string>? __newTitleState;

        /// <summary>State for the _newTitle field: Value, SetSilently, IsDirty, Reset.</summary>
        private global::Tempest.ReactiveState<string> NewTitleState => __newTitleState ??= new global::Tempest.ReactiveState<string>(
            this,
            () => _newTitle,
            __v => _newTitle = __v,
            _newTitle,
            __v => { OnNewTitleChanged(__v); return global::System.Threading.Tasks.Task.CompletedTask; });

        private global::Tempest.ReactiveState<List<TodoItem>>? __todosState;

        /// <summary>State for the _todos field: Value, SetSilently, IsDirty, Reset.</summary>
        private global::Tempest.ReactiveState<List<TodoItem>> TodosState => __todosState ??= new global::Tempest.ReactiveState<List<TodoItem>>(
            this,
            () => _todos,
            __v => _todos = __v,
            _todos,
            null);

        protected override void RegisterTempestHandlers(global::Tempest.IEventBus bus)
        {
            SubscribeEvent<TodoCompleted>(e => DispatchEvent(() => OnTodoCompleted(e)));
            _ = NewTitleState;
            _ = TodosState;
        }
    }
}
