// <auto-generated by Tempest />
// Illustrative: what the C# symbol frontend and the SAME framework-neutral emitter
// produce for DesktopTodo.xaml.cs once the XAML host lands. Identical shape to
// samples/blazor/Todo.Tempest.g.cs — the only difference is that symbol-sourced type
// names arrive fully qualified (text-sourced razor members are emitted as written,
// which is why the razor path carries @using directives along and this path never
// needs any).
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tempest.Samples.Desktop
{
    partial class DesktopTodo
    {
        private global::Tempest.CommandState<global::System.Collections.Generic.List<global::Tempest.Samples.Desktop.TodoItem>>? __loadState;

        /// <summary>State for the Load command: IsLoading, Error, Execute, TryExecute.</summary>
        private global::Tempest.CommandState<global::System.Collections.Generic.List<global::Tempest.Samples.Desktop.TodoItem>> LoadState => __loadState ??= new global::Tempest.CommandState<global::System.Collections.Generic.List<global::Tempest.Samples.Desktop.TodoItem>>(this, __ct => Load(__ct));

        private global::Tempest.CommandState? __addState;

        /// <summary>State for the Add command: IsLoading, Error, Execute, TryExecute.</summary>
        private global::Tempest.CommandState AddState => __addState ??= new global::Tempest.CommandState(this, __ct => Add(__ct));

        private global::Tempest.ReactiveState<string>? __newTitleState;

        /// <summary>State for the _newTitle field: Value, SetSilently, IsDirty, Reset.</summary>
        private global::Tempest.ReactiveState<string> NewTitleState => __newTitleState ??= new global::Tempest.ReactiveState<string>(
            this,
            () => _newTitle,
            __v => _newTitle = __v,
            _newTitle,
            __v => { OnNewTitleChanged(__v); return global::System.Threading.Tasks.Task.CompletedTask; });

        private global::Tempest.ReactiveState<global::System.Collections.Generic.List<global::Tempest.Samples.Desktop.TodoItem>>? __todosState;

        /// <summary>State for the _todos field: Value, SetSilently, IsDirty, Reset.</summary>
        private global::Tempest.ReactiveState<global::System.Collections.Generic.List<global::Tempest.Samples.Desktop.TodoItem>> TodosState => __todosState ??= new global::Tempest.ReactiveState<global::System.Collections.Generic.List<global::Tempest.Samples.Desktop.TodoItem>>(
            this,
            () => _todos,
            __v => _todos = __v,
            _todos,
            null);

        protected override void RegisterTempestHandlers(global::Tempest.IEventBus bus)
        {
            SubscribeEvent<global::Tempest.Samples.Desktop.DesktopTodo.TodoCompleted>(e => DispatchEvent(() => OnTodoCompleted(e)));
            _ = NewTitleState;
            _ = TodosState;
        }
    }
}
